"use client";

import { OutputFormat } from "@/lib/subtitles";
import { Select } from "./ui/Select";

interface SubtitleCue {
  index: number;
  startTime: number;
  endTime: number;
  text: string;
}

interface SubtitleTrack {
  languageCode: string;
  languageName: string;
  isAutoGenerated: boolean;
  cues: SubtitleCue[];
  rawXml?: string;
}

interface VideoPlayerProps {
  videoId: string;
  videoTitle?: string;
  tracks: SubtitleTrack[];
  selectedTrack: number;
  onTrackChange: (index: number) => void;
  selectedFormat: OutputFormat;
  onFormatChange: (format: OutputFormat) => void;
  onDownload: () => void;
}

export function VideoPlayer({
  videoId,
  videoTitle,
  tracks,
  selectedTrack,
  onTrackChange,
  selectedFormat,
  onFormatChange,
  onDownload,
}: VideoPlayerProps) {
  // Safety check: ensure tracks is an array
  const safeTracks = Array.isArray(tracks) ? tracks : [];
  const currentTrack = safeTracks[selectedTrack];

  // Safely get cues for preview
  const previewCues =
    currentTrack?.cues && Array.isArray(currentTrack.cues)
      ? currentTrack.cues.slice(0, 10)
      : [];

  const handleCopyAllText = () => {
    if (currentTrack?.cues && Array.isArray(currentTrack.cues)) {
      const allText = currentTrack.cues
        .map((c: SubtitleCue) => c.text)
        .join("\n");
      navigator.clipboard.writeText(allText);
    }
  };

  return (
    <section className="max-w-[760px] mx-auto w-full px-8 pb-20">
      <div className="bg-[var(--surface)] border border-[var(--border)] rounded-xl overflow-hidden">
        <div className="aspect-video bg-black">
          <iframe
            src={`https://www.youtube.com/embed/${videoId}`}
            title={videoTitle}
            className="w-full h-full"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
            allowFullScreen
          />
        </div>
        <div className="p-6 space-y-4">
          <h2
            style={{
              fontFamily: "'Syne', sans-serif",
              fontSize: 20,
              fontWeight: 700,
              margin: 0,
            }}
          >
            {videoTitle || videoId}
          </h2>
          <div className="flex gap-4 flex-wrap">
            <div className="flex-1 min-w-[150px]">
              <label className="block text-xs text-[var(--text-muted)] mb-1">
                Subtitle Track
              </label>
              <Select
                value={selectedTrack}
                onChange={(e) => onTrackChange(parseInt(e.target.value))}
              >
                {safeTracks.map((track, idx) => (
                  <option key={idx} value={idx}>
                    {track?.languageName || track?.languageCode || "Unknown"}{" "}
                    {track?.isAutoGenerated ? "(Auto-generated)" : ""}
                  </option>
                ))}
              </Select>
            </div>
            <div className="w-32">
              <label className="block text-xs text-[var(--text-muted)] mb-1">
                Format
              </label>
              <Select
                value={selectedFormat}
                onChange={(e) => onFormatChange(e.target.value as OutputFormat)}
              >
                <option value="srt">SRT</option>
                <option value="vtt">VTT</option>
                <option value="txt">TXT</option>
                <option value="json">JSON</option>
                <option value="xml">XML</option>
              </Select>
            </div>
            <div className="flex items-end">
              <button
                onClick={onDownload}
                className="bg-[var(--accent)] text-white px-6 py-2 rounded-lg font-semibold hover:opacity-90 transition-all"
              >
                Download
              </button>
            </div>
          </div>

          {currentTrack && (
            <div className="mt-4">
              <div className="flex justify-between items-center mb-2">
                <label className="text-xs text-[var(--text-muted)]">
                  Preview
                </label>
                <button
                  onClick={handleCopyAllText}
                  className="text-xs text-[var(--accent)] hover:underline"
                >
                  Copy all text
                </button>
              </div>
              <div className="bg-[var(--bg)] border border-[var(--border)] rounded-lg p-4 h-48 overflow-y-auto">
                {previewCues.length > 0 ? (
                  <div className="space-y-2">
                    {previewCues.map((cue: SubtitleCue) => (
                      <div key={cue.index} className="text-sm">
                        <span className="text-[var(--accent)] font-mono text-xs">
                          [{cue.startTime?.toFixed(1) || "0"}s →{" "}
                          {cue.endTime?.toFixed(1) || "0"}s]
                        </span>
                        <p className="text-[var(--text-muted)] mt-1">
                          {cue.text || ""}
                        </p>
                      </div>
                    ))}
                    {currentTrack.cues?.length > 10 && (
                      <p className="text-center text-[var(--text-dim)] text-sm pt-2">
                        + {currentTrack.cues.length - 10} more cues
                      </p>
                    )}
                  </div>
                ) : (
                  <div className="text-center text-[var(--text-dim)] py-8">
                    <p>No subtitle cues available</p>
                    <p className="text-xs mt-2">
                      Try refreshing or selecting a different track
                    </p>
                  </div>
                )}
              </div>
            </div>
          )}
        </div>
      </div>
    </section>
  );
}
