"use client";

import { useState, useCallback, useEffect, useRef } from "react";
import JSZip from "jszip";
import {
  SubtitleTrack,
  convertCues,
  parseYouTubeXml,
  OutputFormat,
  FORMAT_MIME_TYPES,
  sanitizeFilename,
} from "@/lib/subtitles";

export interface PlaylistVideo {
  id: string;
  title: string;
  duration: number;
  thumbnail?: string;
  subtitles?: SubtitleTrack[];
  error?: string;
  status: "pending" | "loading" | "success" | "error";
  retryCount?: number;
}

interface SavedPlaylistData {
  id: string;
  url: string;
  playlistId: string;
  videos: PlaylistVideo[];
  timestamp: number;
  version: string;
}

export interface SavedPlaylistSummary {
  id: string;
  name: string;
  date: Date;
  videoCount: number;
  url: string;
  completedCount?: number;
}

const PLAYLIST_TTL_MS = 7 * 24 * 60 * 60 * 1000;
const STORAGE_VERSION = "1.0";
const RETRY_OPTIONS = { maxRetries: 3, baseDelay: 2000, maxDelay: 10000 };

const delay = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

function triggerDownload(
  content: string,
  fileName: string,
  mimeType: string,
): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = fileName;
  a.click();
  URL.revokeObjectURL(url);
}

export function usePlaylistExtractor(
  showToast?: (message: string, type: "success" | "error" | "info") => void,
) {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [videos, setVideos] = useState<PlaylistVideo[]>([]);
  const [downloadingAll, setDownloadingAll] = useState(false);
  const [currentPlaylistId, setCurrentPlaylistId] = useState<string | null>(
    null,
  );
  const [currentPlaylistUrl, setCurrentPlaylistUrl] = useState<string | null>(
    null,
  );
  const [currentPlaylistName, setCurrentPlaylistName] =
    useState<string>("playlist");
  const [isPaused, setIsPaused] = useState(false);
  const [currentDownloadIndex, setCurrentDownloadIndex] = useState(-1);

  const abortControllerRef = useRef<AbortController | null>(null);
  const isMountedRef = useRef(true);
  const isClientRef = useRef(false);
  const saveTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const isSavingRef = useRef(false);
  const isPausedRef = useRef(false);
  const isStoppedRef = useRef(false);

  useEffect(() => {
    isClientRef.current = true;
    return () => {
      isMountedRef.current = false;
      abortControllerRef.current?.abort();
      if (saveTimeoutRef.current) clearTimeout(saveTimeoutRef.current);
    };
  }, []);

  const saveCurrentVideosToStorage = useCallback(() => {
    if (!isClientRef.current || !currentPlaylistId || isSavingRef.current)
      return;
    if (saveTimeoutRef.current) clearTimeout(saveTimeoutRef.current);

    saveTimeoutRef.current = setTimeout(() => {
      if (currentPlaylistId && videos.length > 0 && isMountedRef.current) {
        isSavingRef.current = true;
        const cleanVideos = videos.map((v) => ({
          id: v.id,
          title: v.title,
          duration: v.duration,
          thumbnail: v.thumbnail,
          status: v.status,
          error: v.error,
          retryCount: v.retryCount,
          subtitles: v.subtitles
            ? v.subtitles.map((t) => ({
                languageCode: t.languageCode,
                languageName: t.languageName,
                isAutoGenerated: t.isAutoGenerated,
                cues: t.cues || [],
                rawXml: t.rawXml !== undefined ? t.rawXml : null,
              }))
            : undefined,
        }));
        const data: SavedPlaylistData = {
          id: currentPlaylistId,
          url: currentPlaylistUrl || "",
          playlistId: currentPlaylistId,
          videos: cleanVideos as PlaylistVideo[],
          timestamp: Date.now(),
          version: STORAGE_VERSION,
        };
        try {
          localStorage.setItem(
            `playlist_${currentPlaylistId}`,
            JSON.stringify(data),
          );
          localStorage.setItem("last_playlist_id", currentPlaylistId);
        } catch (err) {
          console.error("Failed to save to localStorage:", err);
        } finally {
          isSavingRef.current = false;
        }
      }
      saveTimeoutRef.current = null;
    }, 300);
  }, [currentPlaylistId, currentPlaylistUrl, videos]);

  const savePlaylistToStorage = useCallback(
    (
      playlistId: string,
      url: string,
      videosData: PlaylistVideo[],
      name?: string,
    ) => {
      if (!isClientRef.current || !playlistId || videosData.length === 0)
        return;
      const cleanVideos = videosData.map((v) => ({
        id: v.id,
        title: v.title,
        duration: v.duration,
        thumbnail: v.thumbnail,
        status: v.status,
        error: v.error,
        retryCount: v.retryCount,
        subtitles: v.subtitles
          ? v.subtitles.map((t) => ({
              languageCode: t.languageCode,
              languageName: t.languageName,
              isAutoGenerated: t.isAutoGenerated,
              cues: t.cues || [],
              rawXml: t.rawXml !== undefined ? t.rawXml : null,
            }))
          : undefined,
      }));
      const data: SavedPlaylistData = {
        id: playlistId,
        url,
        playlistId,
        videos: cleanVideos as PlaylistVideo[],
        timestamp: Date.now(),
        version: STORAGE_VERSION,
      };
      try {
        localStorage.setItem(`playlist_${playlistId}`, JSON.stringify(data));
        localStorage.setItem("last_playlist_id", playlistId);
        if (name && name !== `Playlist_${playlistId}`) {
          localStorage.setItem(`playlist_${playlistId}_name`, name);
        }
      } catch (err) {
        console.error("Failed to save to localStorage:", err);
      }
    },
    [],
  );

  const loadPlaylistFromStorage = useCallback(
    (playlistId: string): SavedPlaylistData | null => {
      if (!isClientRef.current) return null;
      const raw = localStorage.getItem(`playlist_${playlistId}`);
      if (!raw) return null;
      try {
        const data = JSON.parse(raw) as SavedPlaylistData;
        if (Date.now() - data.timestamp > PLAYLIST_TTL_MS) {
          localStorage.removeItem(`playlist_${playlistId}`);
          return null;
        }
        if (data.videos) {
          data.videos = data.videos.map((v) => ({
            ...v,
            status: v.status || "pending",
            retryCount: v.retryCount || 0,
            subtitles: v.subtitles?.map((t) => ({
              ...t,
              rawXml: t.rawXml === null ? undefined : t.rawXml,
              cues: t.cues || [],
            })),
          }));
        }
        return data;
      } catch {
        return null;
      }
    },
    [],
  );

  const getSavedPlaylists = useCallback((): SavedPlaylistSummary[] => {
    if (!isClientRef.current) return [];
    const results: SavedPlaylistSummary[] = [];
    for (let i = 0; i < localStorage.length; i++) {
      const key = localStorage.key(i);
      if (
        !key?.startsWith("playlist_") ||
        key === "last_playlist_id" ||
        key.endsWith("_name")
      )
        continue;
      try {
        const raw = localStorage.getItem(key);
        if (!raw) continue;
        const data = JSON.parse(raw) as SavedPlaylistData;
        if (data.id && data.videos) {
          const savedName = localStorage.getItem(`playlist_${data.id}_name`);
          const completedCount = data.videos.filter(
            (v) => v.status === "success",
          ).length;
          results.push({
            id: data.id,
            name:
              savedName || data.videos[0]?.title?.substring(0, 50) || data.id,
            date: new Date(data.timestamp),
            videoCount: data.videos.length,
            url: data.url,
            completedCount,
          });
        }
      } catch {
        /* skip */
      }
    }
    return results.sort((a, b) => b.date.getTime() - a.date.getTime());
  }, []);

  const deleteSavedPlaylist = useCallback((playlistId: string) => {
    if (!isClientRef.current) return;
    localStorage.removeItem(`playlist_${playlistId}`);
    localStorage.removeItem(`playlist_${playlistId}_name`);
    if (localStorage.getItem("last_playlist_id") === playlistId) {
      localStorage.removeItem("last_playlist_id");
    }
  }, []);

  const resumeLastPlaylist = useCallback((): SavedPlaylistData | null => {
    if (!isClientRef.current) return null;
    const lastId = localStorage.getItem("last_playlist_id");
    if (!lastId) return null;
    const saved = loadPlaylistFromStorage(lastId);
    if (saved && isMountedRef.current) {
      setCurrentPlaylistId(saved.playlistId);
      setCurrentPlaylistUrl(saved.url);
      setVideos(saved.videos);
      const savedName = localStorage.getItem(
        `playlist_${saved.playlistId}_name`,
      );
      if (savedName) setCurrentPlaylistName(savedName);
      const completedCount = saved.videos.filter(
        (v) => v.status === "success",
      ).length;
      showToast?.(
        `Resumed playlist: ${completedCount}/${saved.videos.length} videos completed`,
        "info",
      );
    }
    return saved;
  }, [loadPlaylistFromStorage, showToast]);

  const updateVideo = useCallback(
    (videoIndex: number, updates: Partial<PlaylistVideo>) => {
      if (!isMountedRef.current) return;
      setVideos((prev) => {
        const next = [...prev];
        if (next[videoIndex])
          next[videoIndex] = { ...next[videoIndex], ...updates };
        return next;
      });
    },
    [],
  );

  const fetchWithRetry = useCallback(
    async (videoId: string, attempt = 0): Promise<SubtitleTrack[]> => {
      try {
        const res = await fetch(`/api/subtitles?url=${videoId}`);
        if (!res.ok) {
          const errorData = await res.json();
          throw new Error(errorData.error ?? `HTTP ${res.status}`);
        }
        const data = await res.json();
        return (data.tracks ?? []) as SubtitleTrack[];
      } catch (err) {
        if (attempt < RETRY_OPTIONS.maxRetries) {
          const backoff = Math.min(
            RETRY_OPTIONS.baseDelay * Math.pow(2, attempt),
            RETRY_OPTIONS.maxDelay,
          );
          await delay(backoff);
          return fetchWithRetry(videoId, attempt + 1);
        }
        throw err;
      }
    },
    [],
  );

  const fetchPlaylist = useCallback(
    async (
      playlistUrl: string,
      maxResults: number,
      forceRefresh = false,
    ): Promise<PlaylistVideo[]> => {
      setLoading(true);
      setError(null);
      try {
        const idMatch = playlistUrl.match(/[?&]list=([A-Za-z0-9_-]+)/);
        const playlistId = idMatch?.[1] ?? null;

        if (!forceRefresh && playlistId && isClientRef.current) {
          const saved = loadPlaylistFromStorage(playlistId);
          if (saved?.videos.length && isMountedRef.current) {
            const completedCount = saved.videos.filter(
              (v) => v.status === "success",
            ).length;
            setCurrentPlaylistId(playlistId);
            setCurrentPlaylistUrl(playlistUrl);
            setVideos(saved.videos);
            const savedName = localStorage.getItem(
              `playlist_${playlistId}_name`,
            );
            setCurrentPlaylistName(savedName || `Playlist_${playlistId}`);
            showToast?.(
              `📀 Loaded saved progress: ${completedCount}/${saved.videos.length} videos completed`,
              "info",
            );
            setLoading(false);
            return saved.videos;
          }
        }

        const res = await fetch(
          `/api/playlist?url=${encodeURIComponent(playlistUrl)}&maxResults=${maxResults}`,
        );
        if (!res.ok) {
          const errorData = await res.json();
          throw new Error(errorData.error ?? `HTTP ${res.status}`);
        }

        const data = await res.json();
        const initialVideos: PlaylistVideo[] = data.videos.map(
          (v: PlaylistVideo) => ({
            ...v,
            status: "pending" as const,
            retryCount: 0,
          }),
        );

        if (isMountedRef.current) {
          setVideos(initialVideos);
          setCurrentPlaylistId(data.playlistId);
          setCurrentPlaylistUrl(playlistUrl);
          const playlistName = data.playlistName || playlistId || "playlist";
          setCurrentPlaylistName(playlistName);
          if (data.playlistId && isClientRef.current) {
            savePlaylistToStorage(
              data.playlistId,
              playlistUrl,
              initialVideos,
              playlistName,
            );
          }
        }
        return initialVideos;
      } catch (err) {
        const message =
          err instanceof Error ? err.message : "Failed to fetch playlist";
        if (isMountedRef.current) setError(message);
        throw err;
      } finally {
        if (isMountedRef.current) setLoading(false);
      }
    },
    [loadPlaylistFromStorage, savePlaylistToStorage, showToast],
  );

  const downloadSubtitlesForVideo = useCallback(
    async (
      videoId: string,
      videoIndex: number,
      format: string,
      delayMs = 0,
    ): Promise<void> => {
      if (delayMs > 0) await delay(delayMs);
      updateVideo(videoIndex, { status: "loading" });
      try {
        const tracks = await fetchWithRetry(videoId);
        if (isMountedRef.current) {
          const parsedTracks = tracks.map((track) => ({
            ...track,
            cues:
              track.cues && track.cues.length > 0
                ? track.cues
                : track.rawXml
                  ? parseYouTubeXml(track.rawXml)
                  : [],
          }));
          updateVideo(videoIndex, {
            status: "success",
            subtitles: parsedTracks,
            error: undefined,
          });
        }
      } catch (err) {
        if (isMountedRef.current) {
          const message = err instanceof Error ? err.message : "Failed";
          updateVideo(videoIndex, {
            status: "error",
            error: message,
            retryCount: (videos[videoIndex]?.retryCount ?? 0) + 1,
          });
        }
      }
    },
    [fetchWithRetry, updateVideo, videos],
  );

  const downloadAllSubtitles = useCallback(
    async (
      delayMs = 3000,
      onProgress?: (current: number, total: number) => void,
    ) => {
      setDownloadingAll(true);
      isPausedRef.current = false;
      isStoppedRef.current = false;

      const currentVideos = videos;
      const pendingVideos = currentVideos.filter((v) => v.status !== "success");
      let processed = 0;

      for (let i = 0; i < currentVideos.length; i++) {
        if (isStoppedRef.current) break;
        if (currentVideos[i].status === "success") continue;

        while (isPausedRef.current && !isStoppedRef.current) {
          await delay(500);
        }
        if (isStoppedRef.current) break;

        setCurrentDownloadIndex(i);
        await downloadSubtitlesForVideo(currentVideos[i].id, i, "srt", 0);
        processed++;
        onProgress?.(processed, pendingVideos.length);
        if (i < currentVideos.length - 1 && !isStoppedRef.current)
          await delay(delayMs);
      }

      setDownloadingAll(false);
      setCurrentDownloadIndex(-1);
    },
    [videos, downloadSubtitlesForVideo],
  );

  const retryAllFailed = useCallback(
    async (delayMs = 3000) => {
      const currentVideos = videos;
      for (let i = 0; i < currentVideos.length; i++) {
        if (currentVideos[i].status !== "error") continue;
        await downloadSubtitlesForVideo(currentVideos[i].id, i, "srt", 0);
        if (i < currentVideos.length - 1) await delay(delayMs);
      }
    },
    [videos, downloadSubtitlesForVideo],
  );

  const resumeIncompleteDownloads = useCallback(
    async (delayMs = 3000) => {
      const currentVideos = videos;
      for (let i = 0; i < currentVideos.length; i++) {
        if (currentVideos[i].status === "success") continue;
        await downloadSubtitlesForVideo(currentVideos[i].id, i, "srt", 0);
        if (i < currentVideos.length - 1) await delay(delayMs);
      }
    },
    [videos, downloadSubtitlesForVideo],
  );

  const pauseDownload = useCallback(() => {
    isPausedRef.current = true;
    setIsPaused(true);
  }, []);

  const resumeDownload = useCallback(() => {
    isPausedRef.current = false;
    setIsPaused(false);
  }, []);

  const stopDownload = useCallback(() => {
    isStoppedRef.current = true;
    isPausedRef.current = false;
    setIsPaused(false);
    setDownloadingAll(false);
    setCurrentDownloadIndex(-1);
  }, []);

  const downloadSingleFile = useCallback(
    (video: PlaylistVideo, trackIndex: number, format = "srt") => {
      const track = video.subtitles?.[trackIndex];
      if (!track) {
        showToast?.("No subtitle track found", "error");
        return;
      }
      const fmt = format as OutputFormat;

      let cues = track.cues;
      if (
        (!cues || cues.length === 0) &&
        track.rawXml &&
        track.rawXml.trim() !== ""
      ) {
        cues = parseYouTubeXml(track.rawXml);
      }

      if (!cues || cues.length === 0) {
        showToast?.("No subtitle data available for this video", "error");
        return;
      }

      const output = convertCues(cues, fmt, track.rawXml);
      if (!output || output.trim() === "") {
        showToast?.("No subtitle content to download", "error");
        return;
      }

      const stem = sanitizeFilename(video.title);
      triggerDownload(
        output,
        `${stem}_${track.languageCode}.${fmt}`,
        FORMAT_MIME_TYPES[fmt],
      );
      showToast?.(`Downloaded ${stem}`, "success");
    },
    [showToast],
  );

  const downloadMultipleFormats = useCallback(
    (video: PlaylistVideo, trackIndex: number, formats: string[]) => {
      const track = video.subtitles?.[trackIndex];
      if (!track) {
        showToast?.("No subtitle track found", "error");
        return;
      }

      let cues = track.cues;
      if (
        (!cues || cues.length === 0) &&
        track.rawXml &&
        track.rawXml.trim() !== ""
      ) {
        cues = parseYouTubeXml(track.rawXml);
      }

      if (!cues || cues.length === 0) {
        showToast?.("No subtitle data available", "error");
        return;
      }

      const zip = new JSZip();
      let hasContent = false;

      for (const format of formats) {
        const fmt = format as OutputFormat;
        const output = convertCues(cues, fmt, track.rawXml);
        if (output && output.trim() !== "") {
          const stem = sanitizeFilename(video.title);
          zip.file(`${stem}_${track.languageCode}.${fmt}`, output);
          hasContent = true;
        }
      }

      if (!hasContent) {
        showToast?.("No subtitle content to download", "error");
        return;
      }

      const stem = sanitizeFilename(video.title);
      zip
        .generateAsync({ type: "blob" })
        .then((zipBlob) => {
          const url = URL.createObjectURL(zipBlob);
          const a = document.createElement("a");
          a.href = url;
          a.download = `${stem}_${track.languageCode}_subtitles.zip`;
          a.click();
          URL.revokeObjectURL(url);
          showToast?.(
            `Downloaded ${formats.length} formats for "${video.title}"`,
            "success",
          );
        })
        .catch(() =>
          showToast?.("Failed to create multi-format download", "error"),
        );
    },
    [showToast],
  );

  const downloadPlaylistAsZip = useCallback(
    async (
      playlistName: string,
      onProgress?: (current: number, total: number) => void,
    ) => {
      const zip = new JSZip();
      const folder = zip.folder(sanitizeFilename(playlistName)) ?? zip;
      let processed = 0;

      const successVideos = videos.filter(
        (v) => v.status === "success" && v.subtitles?.length,
      );
      if (successVideos.length === 0) {
        showToast?.("No completed subtitles to download", "error");
        return;
      }

      for (const video of successVideos) {
        if (!video.subtitles?.length) continue;
        for (const track of video.subtitles) {
          let cues = track.cues;
          if (
            (!cues || cues.length === 0) &&
            track.rawXml &&
            track.rawXml.trim() !== ""
          ) {
            cues = parseYouTubeXml(track.rawXml);
          }

          if (!cues || cues.length === 0) {
            console.warn(`No subtitle data for ${video.title}`);
            processed++;
            onProgress?.(processed, successVideos.length);
            continue;
          }

          const output = convertCues(cues, "srt", track.rawXml);
          if (output && output.trim() !== "") {
            const stem = sanitizeFilename(video.title);
            folder.file(`${stem}_${track.languageCode}.srt`, output);
          }
          processed++;
          onProgress?.(processed, successVideos.length);
        }
      }

      const safeName = sanitizeFilename(playlistName);
      const zipBlob = await zip.generateAsync({ type: "blob" });
      const url = URL.createObjectURL(zipBlob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${safeName}_subtitles.zip`;
      a.click();
      URL.revokeObjectURL(url);
      showToast?.(`Downloaded ${processed} subtitle files`, "success");
    },
    [videos, showToast],
  );

  const downloadAllVideosMultipleFormats = useCallback(
    async (
      formats: string[],
      onProgress?: (current: number, total: number) => void,
    ) => {
      if (formats.length === 0) {
        showToast?.("Please select at least one format", "error");
        return;
      }

      const zip = new JSZip();
      let processed = 0;
      let totalSubtitles = 0;

      for (const video of videos) {
        if (video.subtitles?.length) {
          for (const track of video.subtitles) {
            const hasData =
              (track.cues && track.cues.length > 0) ||
              (track.rawXml && track.rawXml.trim() !== "");
            if (hasData) totalSubtitles += formats.length;
          }
        }
      }

      if (totalSubtitles === 0) {
        showToast?.("No subtitles available to download", "error");
        return;
      }

      showToast?.(`Preparing ${totalSubtitles} subtitle files...`, "info");

      for (const video of videos) {
        if (video.subtitles?.length) {
          for (const track of video.subtitles) {
            let cues = track.cues;
            if (
              (!cues || cues.length === 0) &&
              track.rawXml &&
              track.rawXml.trim() !== ""
            ) {
              cues = parseYouTubeXml(track.rawXml);
            }

            if (!cues || cues.length === 0) {
              for (let i = 0; i < formats.length; i++) {
                processed++;
                onProgress?.(processed, totalSubtitles);
              }
              continue;
            }

            for (const format of formats) {
              const fmt = format as OutputFormat;
              const output = convertCues(cues, fmt, track.rawXml);
              if (output && output.trim() !== "") {
                const stem = sanitizeFilename(video.title);
                zip.file(`${stem}_${track.languageCode}.${fmt}`, output);
              }
              processed++;
              onProgress?.(processed, totalSubtitles);
            }
          }
        }
      }

      const safeName = sanitizeFilename(currentPlaylistName);
      const formatSuffix =
        formats.length === 1 ? formats[0] : `${formats.length}formats`;
      const zipBlob = await zip.generateAsync({ type: "blob" });
      const url = URL.createObjectURL(zipBlob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${safeName}_subtitles_${formatSuffix}.zip`;
      a.click();
      URL.revokeObjectURL(url);
      showToast?.(`Downloaded ${processed} subtitle files`, "success");
    },
    [videos, currentPlaylistName, showToast],
  );

  return {
    videos,
    loading,
    error,
    downloadingAll,
    currentPlaylistId,
    currentPlaylistName,
    isPaused,
    currentDownloadIndex,
    fetchPlaylist,
    savePlaylistToStorage,
    loadPlaylistFromStorage,
    resumeLastPlaylist,
    getSavedPlaylists,
    deleteSavedPlaylist,
    saveCurrentVideosToStorage,
    downloadSubtitlesForVideo,
    downloadAllSubtitles,
    retryAllFailed,
    downloadSingleFile,
    downloadMultipleFormats,
    downloadAllVideosMultipleFormats,
    resumeIncompleteDownloads,
    downloadPlaylistAsZip,
    pauseDownload,
    resumeDownload,
    stopDownload,
  };
}
