import { NextRequest, NextResponse } from "next/server";
import { parseYouTubeXml, sanitizeFilename, stripHtml } from "@/lib/subtitles";

export const dynamic = "force-dynamic";
export const runtime = "nodejs"; // Add this line

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface CaptionTrack {
  languageCode: string;
  name?: { simpleText?: string } | string;
  baseUrl?: string;
  kind?: string;
}

interface Cue {
  index: number;
  startTime: number;
  endTime: number;
  text: string;
}

interface TrackWithCues {
  languageCode: string;
  languageName: string;
  isAutoGenerated: boolean;
  cues: Cue[];
}

interface Json3Event {
  tStartMs?: number;
  segs?: Array<{ utf8?: string }>;
}

interface Json3Data {
  events?: Json3Event[];
}

interface PlayerResponse {
  captions?: {
    playerCaptionsTracklistRenderer?: {
      captionTracks?: CaptionTrack[];
    };
  };
  videoDetails?: {
    title?: string;
  };
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

async function fetchWithTimeout(
  url: string,
  timeoutMs = 10000,
): Promise<Response> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    return await fetch(url, { signal: controller.signal });
  } finally {
    clearTimeout(timer);
  }
}

function extractVideoId(input: string): string | null {
  const patterns = [
    /(?:youtube\.com\/(?:watch\?v=|embed\/|v\/)|youtu\.be\/)([A-Za-z0-9_-]{11})/,
    /^([A-Za-z0-9_-]{11})$/,
  ];
  for (const pattern of patterns) {
    const match = input.match(pattern);
    if (match) return match[1];
  }
  return null;
}

function resolveLanguageName(track: CaptionTrack): string {
  if (!track.name) return track.languageCode;
  return typeof track.name === "object"
    ? (track.name.simpleText ?? track.languageCode)
    : track.name;
}

// ---------------------------------------------------------------------------
// Get Innertube API Key
// ---------------------------------------------------------------------------

async function getInnertubeApiKey(videoId: string): Promise<string | null> {
  try {
    const res = await fetch(`https://www.youtube.com/watch?v=${videoId}`, {
      headers: {
        "User-Agent":
          "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        Accept:
          "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
        "Accept-Language": "en-US,en;q=0.5",
        "Cache-Control": "no-cache",
        Pragma: "no-cache",
      },
    });

    if (!res.ok) return null;

    const html = await res.text();
    const patterns = [
      /"INNERTUBE_API_KEY":"([^"]+)"/,
      /"innertubeApiKey":"([^"]+)"/,
      /innertubeApiKey:\s*"([^"]+)"/,
    ];
    for (const pattern of patterns) {
      const match = html.match(pattern);
      if (match) return match[1];
    }
    return null;
  } catch {
    return null;
  }
}

// ---------------------------------------------------------------------------
// Fetch Caption Tracks
// ---------------------------------------------------------------------------

async function fetchCaptionTracks(
  videoId: string,
): Promise<{ tracks: CaptionTrack[]; title?: string }> {
  const apiKey = await getInnertubeApiKey(videoId);
  if (!apiKey) {
    throw new Error("Failed to extract API key from YouTube");
  }

  const payload = {
    videoId,
    context: {
      client: {
        clientName: "ANDROID",
        clientVersion: "20.10.38",
        androidSdkVersion: 30,
        hl: "en",
        gl: "US",
      },
    },
  };

  const res = await fetch(
    `https://www.youtube.com/youtubei/v1/player?key=${apiKey}`,
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "User-Agent":
          "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        Accept: "*/*",
        "Accept-Language": "en-US,en;q=0.9",
        Origin: "https://www.youtube.com",
        Referer: `https://www.youtube.com/watch?v=${videoId}`,
      },
      body: JSON.stringify(payload),
    },
  );

  if (!res.ok) {
    const errorText = await res.text().catch(() => "Unknown error");
    throw new Error(`Failed to fetch video data: ${res.status} - ${errorText}`);
  }

  const data = (await res.json()) as PlayerResponse;
  return {
    tracks:
      data?.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [],
    title: data?.videoDetails?.title,
  };
}

// ---------------------------------------------------------------------------
// Parse JSON3 Format
// ---------------------------------------------------------------------------

function parseJson3Format(jsonData: Json3Data): Cue[] {
  const cues: Cue[] = [];
  if (!jsonData.events) return cues;

  let index = 1;
  let currentStartMs = 0;
  let currentText = "";

  for (const event of jsonData.events) {
    if (event.tStartMs !== undefined) {
      if (currentText) {
        cues.push({
          index: index++,
          startTime: currentStartMs / 1000,
          endTime: (event.tStartMs || currentStartMs + 5000) / 1000,
          text: currentText.trim(),
        });
      }
      currentStartMs = event.tStartMs;
      currentText = "";
    }

    if (event.segs) {
      for (const seg of event.segs) {
        if (seg.utf8) currentText += seg.utf8;
      }
    }
  }

  if (currentText) {
    cues.push({
      index: index++,
      startTime: currentStartMs / 1000,
      endTime: (currentStartMs + 5000) / 1000,
      text: currentText.trim(),
    });
  }

  return cues;
}

// ---------------------------------------------------------------------------
// Fetch Track Cues
// ---------------------------------------------------------------------------

async function fetchTrackCues(
  track: CaptionTrack,
): Promise<TrackWithCues | null> {
  if (!track.baseUrl) return null;

  const baseUrl = track.baseUrl.replace(/&fmt=\w+$/, "");
  const res = await fetchWithTimeout(`${baseUrl}&fmt=json3`);
  if (!res.ok) return null;

  const raw = await res.text();
  let cues: Cue[] = [];

  try {
    const jsonData = JSON.parse(raw) as Json3Data;
    cues = jsonData.events ? parseJson3Format(jsonData) : parseYouTubeXml(raw);
  } catch {
    cues = parseYouTubeXml(raw);
  }

  return {
    languageCode: track.languageCode,
    languageName: resolveLanguageName(track),
    isAutoGenerated: track.kind === "asr",
    cues,
  };
}

// ---------------------------------------------------------------------------
// Route Handler
// ---------------------------------------------------------------------------

export async function GET(request: NextRequest): Promise<NextResponse> {
  try {
    const { searchParams } = new URL(request.url);
    const input = searchParams.get("url") ?? searchParams.get("videoId") ?? "";

    if (!input) {
      return NextResponse.json(
        { error: "Missing url or videoId parameter" },
        { status: 400 },
      );
    }

    const videoId = extractVideoId(input);
    if (!videoId) {
      return NextResponse.json(
        { error: "Invalid YouTube URL or video ID" },
        { status: 400 },
      );
    }

    const { tracks, title } = await fetchCaptionTracks(videoId);

    if (tracks.length === 0) {
      return NextResponse.json(
        { error: "No subtitles available for this video" },
        { status: 404 },
      );
    }

    const settled = await Promise.allSettled(tracks.map(fetchTrackCues));

    const validTracks = settled
      .filter(
        (r): r is PromiseFulfilledResult<TrackWithCues> =>
          r.status === "fulfilled" &&
          r.value !== null &&
          r.value.cues.length > 0,
      )
      .map((r) => r.value);

    if (validTracks.length === 0) {
      return NextResponse.json(
        { error: "Could not fetch subtitle content" },
        { status: 500 },
      );
    }

    const videoTitle = sanitizeFilename(title ?? videoId);

    return NextResponse.json({ videoId, videoTitle, tracks: validTracks });
  } catch (err) {
    console.error("Subtitles API error:", err);
    const message = err instanceof Error ? err.message : "Unknown error";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
