// lib/subtitles.ts

export interface SubtitleCue {
  index: number;
  startTime: number;
  endTime: number;
  text: string;
}

export interface SubtitleTrack {
  languageCode: string;
  languageName: string;
  isAutoGenerated: boolean;
  cues: SubtitleCue[];
  rawXml?: string;
}

export type OutputFormat = "srt" | "vtt" | "txt" | "json" | "xml";

export const FILENAME_UNSAFE_RE = /[<>:"/\\|?*]/g;

export const FORMAT_EXTENSIONS: Record<OutputFormat, string> = {
  srt: ".srt",
  vtt: ".vtt",
  txt: ".txt",
  json: ".json",
  xml: ".xml",
};

export const FORMAT_MIME_TYPES: Record<OutputFormat, string> = {
  srt: "text/plain",
  vtt: "text/vtt",
  txt: "text/plain",
  json: "application/json",
  xml: "application/xml",
};

export function sanitizeFilename(raw: string, maxLength = 100): string {
  return raw.replace(FILENAME_UNSAFE_RE, "").trim().substring(0, maxLength);
}

function toSrtTimestamp(seconds: number): string {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = Math.floor(seconds % 60);
  const ms = Math.round((seconds - Math.floor(seconds)) * 1000);
  return `${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")},${String(ms).padStart(3, "0")}`;
}

function toVttTimestamp(seconds: number): string {
  return toSrtTimestamp(seconds).replace(",", ".");
}

export function stripHtml(html: string): string {
  return html
    .replace(/<[^>]+>/g, "")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;|&#x27;/g, "'")
    .replace(/&nbsp;/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function stripSTimingTags(text: string): string {
  return text.includes("<s")
    ? text.replace(/<s[^>]*>/g, "").replace(/<\/s>/g, "")
    : text;
}

export function extractVideoId(input: string): string | null {
  const patterns = [
    /(?:youtube\.com\/(?:watch\?v=|embed\/|v\/)|youtu\.be\/)([A-Za-z0-9_-]{11})/,
    /^([A-Za-z0-9_-]{11})$/,
  ];
  for (const pattern of patterns) {
    const match = input.match(pattern);
    if (match) return match[1];
  }
  return null;
}

export function extractPlaylistId(input: string): string | null {
  const patterns = [/[?&]list=([A-Za-z0-9_-]+)/, /^([A-Za-z0-9_-]{12,})/];
  for (const pattern of patterns) {
    const match = input.match(pattern);
    if (match) return match[1];
  }
  return null;
}

export function parseYouTubeXml(xml: string): SubtitleCue[] {
  const cues: SubtitleCue[] = [];
  let index = 1;

  let match: RegExpExecArray | null;

  const textRe =
    /<text\s+start="([^"]+)"\s+dur="([^"]+)"[^>]*>([\s\S]*?)<\/text>/gi;
  while ((match = textRe.exec(xml)) !== null) {
    const start = parseFloat(match[1]);
    const dur = parseFloat(match[2]);
    const text = stripHtml(stripSTimingTags(match[3]));
    if (text && !Number.isNaN(start) && !Number.isNaN(dur)) {
      cues.push({
        index: index++,
        startTime: start,
        endTime: start + dur,
        text,
      });
    }
  }

  if (cues.length > 0) return cues;

  const pRe = /<p\b[^>]*\bt="(\d+)"[^>]*\bd="(\d+)"[^>]*>([\s\S]*?)<\/p>/gi;
  while ((match = pRe.exec(xml)) !== null) {
    const startMs = parseInt(match[1], 10);
    const durMs = parseInt(match[2], 10);
    const text = stripHtml(stripSTimingTags(match[3]));
    if (text && !Number.isNaN(startMs) && !Number.isNaN(durMs)) {
      cues.push({
        index: index++,
        startTime: startMs / 1000,
        endTime: (startMs + durMs) / 1000,
        text,
      });
    }
  }

  return cues;
}

// ADD THIS FUNCTION - parseSubtitleContent
export function parseSubtitleContent(content: string): SubtitleCue[] {
  if (!content || typeof content !== "string" || content.trim() === "") {
    return [];
  }

  // Check if it looks like SRT format
  if (
    /\d{2}:\d{2}:\d{2}[,.]\d{3}\s*-->\s*\d{2}:\d{2}:\d{2}[,.]\d{3}/.test(
      content,
    )
  ) {
    return parseSrt(content);
  }

  // Otherwise try XML parser
  return parseYouTubeXml(content);
}

// ADD THIS FUNCTION - parseSrt (for SRT format support)
export function parseSrt(srt: string): SubtitleCue[] {
  if (!srt || typeof srt !== "string" || srt.trim() === "") {
    return [];
  }

  const cues: SubtitleCue[] = [];
  const blocks = srt.trim().split(/\n\s*\n/);

  for (const block of blocks) {
    const lines = block.split("\n").filter((line) => line.trim());
    if (lines.length < 2) continue;

    let timeLineIndex = -1;
    let timeLine = "";

    for (let i = 0; i < lines.length; i++) {
      if (lines[i].includes("-->")) {
        timeLineIndex = i;
        timeLine = lines[i];
        break;
      }
    }

    if (timeLineIndex === -1 || !timeLine) continue;

    const timeMatch = timeLine.match(
      /(\d{2}:\d{2}:\d{2}[,.]\d{3})\s*-->\s*(\d{2}:\d{2}:\d{2}[,.]\d{3})/,
    );
    if (!timeMatch) continue;

    const parseTime = (timeStr: string): number => {
      const normalized = timeStr.replace(",", ".");
      const [hms, ms] = normalized.split(".");
      const [h, m, s] = hms.split(":").map(Number);
      return h * 3600 + m * 60 + s + (Number(ms) || 0) / 1000;
    };

    const startTime = parseTime(timeMatch[1]);
    const endTime = parseTime(timeMatch[2]);
    const textLines = lines.slice(timeLineIndex + 1);
    const text = textLines.join("\n").trim();

    if (text && !isNaN(startTime) && !isNaN(endTime) && startTime < endTime) {
      cues.push({
        index: cues.length + 1,
        startTime,
        endTime,
        text,
      });
    }
  }

  return cues;
}

export function toSrt(cues: SubtitleCue[]): string {
  return cues
    .map(
      (c) =>
        `${c.index}\n${toSrtTimestamp(c.startTime)} --> ${toSrtTimestamp(c.endTime)}\n${c.text}\n`,
    )
    .join("\n");
}

export function toVtt(cues: SubtitleCue[]): string {
  const body = cues
    .map(
      (c) =>
        `${toVttTimestamp(c.startTime)} --> ${toVttTimestamp(c.endTime)}\n${c.text}`,
    )
    .join("\n\n");
  return `WEBVTT\n\n${body}`;
}

export function toTxt(cues: SubtitleCue[]): string {
  return cues.map((c) => c.text).join("\n");
}

export function toJson(cues: SubtitleCue[]): string {
  return JSON.stringify(
    cues.map((c) => ({
      index: c.index,
      start: c.startTime,
      end: c.endTime,
      text: c.text,
    })),
    null,
    2,
  );
}

export function convertCues(
  cues: SubtitleCue[],
  format: OutputFormat,
  rawXml?: string,
): string {
  switch (format) {
    case "srt":
      return toSrt(cues);
    case "vtt":
      return toVtt(cues);
    case "txt":
      return toTxt(cues);
    case "json":
      return toJson(cues);
    case "xml":
      return rawXml ?? "";
    default:
      return toSrt(cues);
  }
}

export function getMimeType(format: OutputFormat): string {
  return FORMAT_MIME_TYPES[format];
}
