"use client";

import { useState } from "react";
import VideoControls from "../VideoControls";

interface SubtitleTrack {
  languageCode: string;
  languageName: string;
  isAutoGenerated: boolean;
  cues: any[];
  rawXml?: string;
}

interface PlaylistVideo {
  id: string;
  title: string;
  duration: number;
  thumbnail?: string;
  subtitles?: SubtitleTrack[];
  error?: string;
  status: "pending" | "loading" | "success" | "error";
  retryCount?: number;
}

interface PlaylistVideoItemProps {
  video: PlaylistVideo;
  index: number;
  isDownloading: boolean;
  selectedFormat: string;
  onStart: () => void;
  onDownloadSingle: (trackIndex: number, format: string) => void;
  onDownloadMultiple: (trackIndex: number, formats: string[]) => void;
  onPause: () => void;
  onResume: () => void;
  onStop: () => void;
  progress?: number;
}

const AVAILABLE_FORMATS = [
  { value: "srt", label: "SRT", icon: "📄" },
  { value: "vtt", label: "VTT", icon: "🎬" },
  { value: "txt", label: "TXT", icon: "📝" },
  { value: "json", label: "JSON", icon: "{}" },
  { value: "xml", label: "XML", icon: "📋" },
];

export function PlaylistVideoItem({
  video, index, isDownloading, selectedFormat,
  onStart, onDownloadSingle, onDownloadMultiple,
  onPause, onResume, onStop, progress = 0,
}: PlaylistVideoItemProps) {
  const [selectedFormats, setSelectedFormats] = useState<Set<string>>(new Set());
  const [showFormatPicker, setShowFormatPicker] = useState(false);

  const toggleFormat = (format: string) => {
    setSelectedFormats((prev) => {
      const next = new Set(prev);
      next.has(format) ? next.delete(format) : next.add(format);
      return next;
    });
  };

  const handleMultipleDownload = (trackIndex: number) => {
    const formats = Array.from(selectedFormats);
    if (formats.length === 0) {
      onDownloadSingle(trackIndex, selectedFormat);
    } else {
      onDownloadMultiple(trackIndex, formats);
    }
    setShowFormatPicker(false);
  };

  return (
    <div style={{ background: "var(--surface)", border: "1px solid var(--border)", borderRadius: 12, padding: 16 }}>
      <div style={{ display: "flex", gap: 12, alignItems: "start" }}>
        {video.thumbnail && (
          <img src={video.thumbnail} alt={video.title}
            style={{ width: 80, height: 45, objectFit: "cover", borderRadius: 6, flexShrink: 0 }} />
        )}
        <div style={{ flex: 1, minWidth: 0 }}>
          <div style={{ fontWeight: 600, fontSize: 14, color: "var(--text)", marginBottom: 4 }}>{video.title}</div>

          {video.error && <div style={{ fontSize: 12, color: "#f87171", marginBottom: 8 }}>⚠ {video.error}</div>}

          {video.subtitles && video.subtitles.length > 0 && (
            <div style={{ marginTop: 8 }}>
              {video.subtitles.map((track, trackIdx) => (
                <div key={trackIdx} style={{ marginBottom: 12 }}>
                  <div style={{ display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap", marginBottom: 8 }}>
                    <span style={{ fontSize: 13, fontWeight: 500, color: "var(--text-muted)", minWidth: 100 }}>
                      {track.languageName}:
                    </span>
                    <select
                      onChange={(e) => { if (e.target.value) { onDownloadSingle(trackIdx, e.target.value); e.target.value = ""; } }}
                      defaultValue=""
                      style={{ background: "var(--surface-2)", border: "1px solid var(--border)", borderRadius: 6, padding: "6px 12px", fontSize: 12, color: "var(--text)", cursor: "pointer" }}
                    >
                      <option value="" disabled>Quick download...</option>
                      {AVAILABLE_FORMATS.map((f) => (
                        <option key={f.value} value={f.value}>{f.icon} {f.label}</option>
                      ))}
                    </select>
                    <button
                      onClick={() => setShowFormatPicker(!showFormatPicker)}
                      style={{ background: "var(--surface-2)", border: "1px solid var(--border)", borderRadius: 6, padding: "6px 12px", fontSize: 12, color: "var(--accent)", cursor: "pointer", display: "flex", alignItems: "center", gap: 4 }}
                    >
                      <span>📦</span> Multi-format
                    </button>
                  </div>

                  {showFormatPicker && (
                    <div style={{ background: "var(--bg)", border: "1px solid var(--border)", borderRadius: 8, padding: 12, marginTop: 8, marginBottom: 8 }}>
                      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 12 }}>
                        <span style={{ fontSize: 12, fontWeight: 500, color: "var(--text-muted)" }}>Select formats:</span>
                        <div style={{ display: "flex", gap: 8 }}>
                          <button onClick={() => setSelectedFormats(new Set(AVAILABLE_FORMATS.map((f) => f.value)))}
                            style={{ fontSize: 11, background: "transparent", border: "1px solid var(--border)", borderRadius: 4, padding: "4px 8px", color: "var(--text-muted)", cursor: "pointer" }}>
                            Select All
                          </button>
                          <button onClick={() => setSelectedFormats(new Set())}
                            style={{ fontSize: 11, background: "transparent", border: "1px solid var(--border)", borderRadius: 4, padding: "4px 8px", color: "var(--text-muted)", cursor: "pointer" }}>
                            Clear
                          </button>
                        </div>
                      </div>
                      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(100px, auto))", gap: 8, marginBottom: 12 }}>
                        {AVAILABLE_FORMATS.map((format) => (
                          <label key={format.value} style={{ display: "flex", alignItems: "center", gap: 8, padding: "6px 10px", background: "var(--surface-2)", borderRadius: 6, cursor: "pointer" }}>
                            <input type="checkbox" checked={selectedFormats.has(format.value)} onChange={() => toggleFormat(format.value)}
                              style={{ width: 16, height: 16, cursor: "pointer", accentColor: "var(--accent)" }} />
                            <span style={{ fontSize: 13 }}>{format.icon} {format.label}</span>
                          </label>
                        ))}
                      </div>
                      <div style={{ display: "flex", gap: 8, justifyContent: "flex-end" }}>
                        <button onClick={() => setShowFormatPicker(false)}
                          style={{ padding: "6px 12px", fontSize: 12, background: "var(--surface-2)", border: "1px solid var(--border)", borderRadius: 6, color: "var(--text-muted)", cursor: "pointer" }}>
                          Cancel
                        </button>
                        <button onClick={() => handleMultipleDownload(trackIdx)}
                          style={{ padding: "6px 16px", fontSize: 12, background: "var(--accent)", border: "none", borderRadius: 6, color: "white", cursor: "pointer", fontWeight: 500 }}>
                          Download {selectedFormats.size} Format{selectedFormats.size !== 1 ? "s" : ""}
                        </button>
                      </div>
                    </div>
                  )}
                </div>
              ))}
            </div>
          )}

          <div style={{ display: "flex", gap: 8, marginTop: 12, flexWrap: "wrap" }}>
            <VideoControls
              videoId={video.id} videoIndex={index}
              status={video.status} isDownloading={isDownloading}
              onStart={onStart} onPause={onPause} onResume={onResume} onStop={onStop}
              progress={progress} onRetry={onStart} onClear={onStop}
            />
          </div>
        </div>
      </div>
    </div>
  );
}
