"use client";

import { useMemo, useState } from "react";
import { PlaylistFilters } from "./PlaylistFilters";
import { PlaylistVideoItem } from "./PlaylistVideoItem";
import { PlaylistStatus } from "./PlaylistStatus";
import { PlaylistZipDownload } from "./PlaylistZipDownload";
import { SavedPlaylistsModal } from "../modals/SavedPlaylistsModal";

type FilterType = "all" | "success" | "error" | "pending";

interface SubtitleTrack {
  languageCode: string;
  languageName: string;
  isAutoGenerated: boolean;
  cues: any[];
  baseUrl?: string;
  rawXml?: string;
}

interface PlaylistVideo {
  id: string;
  title: string;
  duration: number;
  thumbnail?: string;
  subtitles?: SubtitleTrack[];
  error?: string;
  status: "pending" | "loading" | "success" | "error";
  retryCount?: number;
}

interface SavedPlaylist {
  id: string;
  name: string;
  date: Date;
  videoCount: number;
  url: string;
  completedCount?: number;
}

interface PlaylistContainerProps {
  videos: PlaylistVideo[];
  statusCounts: {
    all: number;
    success: number;
    error: number;
    pending: number;
  };
  selectedFormat: string;
  filterType: FilterType;
  playlistName: string;
  hasIncomplete: boolean;
  isResuming: boolean;
  isStartingAll: boolean;
  retryingAll: boolean;
  isPaused: boolean;
  downloadingAll: boolean;
  downloadProgress: { current: number; total: number };
  savedPlaylists: SavedPlaylist[];
  currentPlaylistId: string | null;
  onFilterChange: (filter: FilterType) => void;
  onVideoStart: (videoId: string, index: number) => void;
  onDownloadSingle: (
    video: PlaylistVideo,
    trackIndex: number,
    format: string,
  ) => void;
  onDownloadMultiple: (
    video: PlaylistVideo,
    trackIndex: number,
    formats: string[],
  ) => void;
  onResumeIncomplete: () => void;
  onDownloadZip: (
    onProgress: (current: number, total: number) => void,
  ) => Promise<void>;
  onRetryFailed: () => void;
  onStartAll: () => void;
  onDownloadAllMultipleFormats: (formats: string[]) => Promise<void>;
  onPauseDownload: () => void;
  onResumeDownload: () => void;
  onStopDownload: () => void;
  onSaveProgress: () => void;
  onLoadPlaylist: (playlistId: string, url: string) => void;
  onDeletePlaylist: (playlistId: string) => void;
}

export function PlaylistContainer({
  videos,
  statusCounts,
  selectedFormat,
  filterType,
  playlistName,
  hasIncomplete,
  isResuming,
  isStartingAll,
  retryingAll,
  isPaused,
  downloadingAll,
  downloadProgress,
  savedPlaylists,
  currentPlaylistId,
  onFilterChange,
  onVideoStart,
  onDownloadSingle,
  onDownloadMultiple,
  onResumeIncomplete,
  onDownloadZip,
  onRetryFailed,
  onStartAll,
  onDownloadAllMultipleFormats,
  onPauseDownload,
  onResumeDownload,
  onStopDownload,
  onSaveProgress,
  onLoadPlaylist,
  onDeletePlaylist,
}: PlaylistContainerProps) {
  const [isModalOpen, setIsModalOpen] = useState(false);

  const filteredVideos = useMemo(() => {
    return videos.filter(
      (video) => filterType === "all" || video.status === filterType,
    );
  }, [videos, filterType]);

  const hasFailed = statusCounts.error > 0;
  const hasPending = statusCounts.pending > 0;
  const remainingCount = statusCounts.pending + statusCounts.error;
  const percentComplete =
    statusCounts.all > 0
      ? Math.round((statusCounts.success / statusCounts.all) * 100)
      : 0;

  return (
    <section className="max-w-[760px] mx-auto w-full px-8 pb-20">
      <SavedPlaylistsModal
        isOpen={isModalOpen}
        onClose={() => setIsModalOpen(false)}
        playlists={savedPlaylists}
        currentPlaylistId={currentPlaylistId}
        onLoad={(playlistId, url) => {
          onLoadPlaylist(playlistId, url);
          setIsModalOpen(false);
        }}
        onDelete={onDeletePlaylist}
      />

      {/* REMOVED: GlobalFormatSelector component */}

      <PlaylistStatus
        videos={videos}
        onRetryFailed={onRetryFailed}
        onResumeIncomplete={onResumeIncomplete}
        hasIncomplete={hasIncomplete}
        hasFailed={hasFailed}
        isResuming={isResuming}
        retryingAll={retryingAll}
      />

      {/* Action Buttons */}
      <div className="flex gap-3 mb-6 flex-wrap items-center">
        {downloadingAll && (
          <>
            <button
              onClick={onPauseDownload}
              disabled={isPaused}
              className="px-5 py-2.5 text-sm font-semibold rounded-lg bg-yellow-600 text-white hover:bg-yellow-700 disabled:opacity-50 flex items-center gap-2"
            >
              ⏸ Pause
            </button>
            <button
              onClick={onResumeDownload}
              disabled={!isPaused}
              className="px-5 py-2.5 text-sm font-semibold rounded-lg bg-green-600 text-white hover:bg-green-700 disabled:opacity-50 flex items-center gap-2"
            >
              ▶ Resume
            </button>
            <button
              onClick={onStopDownload}
              className="px-5 py-2.5 text-sm font-semibold rounded-lg bg-red-600 text-white hover:bg-red-700 flex items-center gap-2"
            >
              ⏹ Stop
            </button>
          </>
        )}

        {(hasPending || hasIncomplete) && !downloadingAll && (
          <button
            onClick={onStartAll}
            disabled={isStartingAll}
            className="px-5 py-2.5 text-sm font-semibold rounded-lg bg-[var(--accent)] text-white hover:opacity-90 disabled:opacity-50 flex items-center gap-2"
          >
            {isStartingAll ? (
              <>
                <span className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                Downloading... ({statusCounts.success}/{statusCounts.all})
              </>
            ) : (
              <>▶ Start All ({remainingCount} remaining)</>
            )}
          </button>
        )}

        {hasIncomplete && !hasPending && !downloadingAll && (
          <button
            onClick={onResumeIncomplete}
            disabled={isResuming}
            className="px-5 py-2.5 text-sm font-semibold rounded-lg bg-blue-600 text-white hover:bg-blue-700 disabled:opacity-50 flex items-center gap-2"
          >
            {isResuming ? "Resuming..." : `↺ Resume (${remainingCount} left)`}
          </button>
        )}

        <button
          onClick={onSaveProgress}
          disabled={isStartingAll || isResuming}
          className="px-5 py-2.5 text-sm font-semibold rounded-lg bg-[var(--surface-2)] border border-[var(--border)] text-[var(--text)] hover:bg-[var(--surface)] disabled:opacity-50 flex items-center gap-2"
        >
          💾 Save Progress ({percentComplete}%)
        </button>

        <button
          onClick={() => setIsModalOpen(true)}
          className="px-5 py-2.5 text-sm font-semibold rounded-lg bg-[var(--surface-2)] border border-[var(--border)] text-[var(--text)] hover:bg-[var(--surface)] flex items-center gap-2"
        >
          📋 Saved Playlists ({savedPlaylists.length})
        </button>

        {statusCounts.success > 0 && (
          <PlaylistZipDownload
            playlistName={playlistName}
            onDownloadZip={onDownloadZip}
            disabled={isStartingAll || isResuming}
          />
        )}
      </div>

      {downloadingAll && downloadProgress.total > 0 && (
        <div className="mb-4 p-3 bg-[var(--surface)] border border-[var(--border)] rounded-lg">
          <div className="flex justify-between text-xs text-[var(--text-muted)] mb-1">
            <span>Downloading playlist...</span>
            <span>
              {downloadProgress.current} / {downloadProgress.total} videos
            </span>
          </div>
          <div className="w-full h-2 bg-[var(--surface-2)] rounded-full overflow-hidden">
            <div
              className="h-full bg-[var(--accent)] transition-all duration-300"
              style={{
                width: `${(downloadProgress.current / downloadProgress.total) * 100}%`,
              }}
            />
          </div>
          {isPaused && (
            <div className="text-xs text-yellow-500 mt-2 text-center">
              ⏸ Paused — click Resume to continue
            </div>
          )}
        </div>
      )}

      <PlaylistFilters
        filterType={filterType}
        statusCounts={statusCounts}
        onFilterChange={onFilterChange}
      />

      <div className="flex flex-col gap-3">
        {filteredVideos.map((video) => (
          <PlaylistVideoItem
            key={video.id}
            video={video}
            index={videos.findIndex((v) => v.id === video.id)}
            isDownloading={
              downloadingAll &&
              videos.findIndex((v) => v.id === video.id) ===
                downloadProgress.current
            }
            selectedFormat={selectedFormat}
            onStart={() =>
              onVideoStart(
                video.id,
                videos.findIndex((v) => v.id === video.id),
              )
            }
            onDownloadSingle={(trackIndex, format) =>
              onDownloadSingle(video, trackIndex, format)
            }
            onDownloadMultiple={(trackIndex, formats) =>
              onDownloadMultiple(video, trackIndex, formats)
            }
            onPause={onPauseDownload}
            onResume={onResumeDownload}
            onStop={onStopDownload}
          />
        ))}
        {filteredVideos.length === 0 && (
          <div className="text-center py-10 text-[var(--text-muted)]">
            No videos match the selected filter
          </div>
        )}
      </div>
    </section>
  );
}
